### ISSUE TITLE
the configs aren't working for Titan and Centaur

### ISSUE THREAD

**Issue by spacefacey** [Bellabong/Bella_TU#1]
Just that, everything else works fine but titan and centaur aren't working.

**Comment by Gordon-Dry** [comment]
Some of the Titan fuel tanks  are borked, but not all.
I have to boot up KSP but afaik only one Titan fuel tank had some of the texture switch entries borked.
Perhaps more, but not all of them are unlocked?
btw I'm on https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/apollo-saturn-revamp
Centaur I need to see myself first, so I neither can confirm nor disagree.
