### ISSUE TITLE
Z-fighting on GATV

### ISSUE THREAD

**Issue by ballisticfox** [Bellabong/Bella_TU#3]
![image](https://user-images.githubusercontent.com/77298148/170833701-421cb105-4fe1-41c3-babd-4b8b0862901d.png)

**Comment by ballisticfox** [comment]
Latest TU, Bella_TU and BDB version

**Comment by flyboy425** [comment]
Having this issue again with the most recent versions of BDB, TU and 1.0 Bella.

**Comment by Bellabong** [comment]
fixed as per 30024f4
